INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (6, 59, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (7, 59, 'chaussures');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (8, 60, 'landing page');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (9, 60, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (10, 62, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (11, 5, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (12, 5, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (13, 6, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (14, 6, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (15, 7, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (16, 7, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (17, 10, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (18, 11, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (19, 19, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (20, 19, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (21, 19, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (22, 11, 'landing page');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (23, 11, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (24, 12, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (25, 47, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (26, 47, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (27, 48, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (28, 48, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (29, 46, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (30, 46, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (31, 63, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (32, 63, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (33, 63, 'product design');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (34, 62, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (35, 56, 'product design');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (36, 55, 'UI');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (37, 55, 'refonte graphique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (38, 57, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (39, 57, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (40, 58, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (41, 58, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (42, 60, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (43, 39, 'front end ');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (44, 39, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (45, 23, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (46, 23, 'CMS');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (47, 23, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (48, 23, 'back end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (49, 21, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (50, 18, 'CMS');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (51, 18, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (52, 18, 'back end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (53, 18, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (54, 24, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (55, 24, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (56, 35, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (57, 35, 'UI');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (58, 38, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (59, 38, 'UI');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (60, 38, 'UX');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (61, 49, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (62, 49, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (63, 51, 'UX');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (64, 51, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (65, 6, 'nourriture');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (66, 59, 'chaussures');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (67, 47, 'musique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (68, 48, 'musique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (69, 41, 'architecture');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (70, 32, 'transports');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (71, 56, 'films');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (72, 57, 'films');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (73, 60, 'jeux vidéo');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (74, 60, 'refonte graphique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (75, 60, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (76, 54, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (77, 57, 'films');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (78, 44, 'branding');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (79, 42, 'branding');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (80, 43, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (81, 35, 'refonte graphique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (82, 36, 'product design');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (83, 32, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (84, 32, 'landing page');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (85, 33, 'sacs');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (86, 33, 'landing page');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (87, 33, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (88, 25, 'start up');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (89, 25, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (90, 25, 'project development');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (91, 28, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (92, 28, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (93, 28, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (94, 50, 'nourriture');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (95, 51, 'nourriture');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (96, 50, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (97, 50, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (98, 50, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (99, 53, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (100, 53, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (101, 53, 'photographie');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (102, 64, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (103, 64, 'Desktop');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (104, 66, '3D');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (105, 68, 'app mobile');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (106, 68, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (107, 68, 'musique');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (108, 71, 'e-commerce');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (109, 82, 'landing page');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (110, 82, 'responsive');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (111, 82, 'energie');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (112, 84, 'illustration');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (113, 84, 'Adobe Illustrator');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (114, 85, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (115, 85, 'UX');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (116, 85, 'sport');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (117, 87, 'branding');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (118, 87, 'illustrator');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (119, 87, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (120, 88, 'branding');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (121, 88, 'illustrator');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (122, 88, 'daily challenge');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (123, 103, 'responsive');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (124, 103, 'front end');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (125, 103, 'UI');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (126, 104, 'illustration');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (127, 104, 'illustrator');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (128, 105, 'NFT');
INSERT INTO coordinate.secondary_tag (id, project_id, name) VALUES (129, 105, 'app mobile');
